add spanish
chrisbolin/offline pull request #1
Opened 2017-08-31 09:44 UTC by jblancogl

Hi Chris, i´ve loved your project and i've translated it to spanish. Maybe you will be interested by the translation?
Thank you for the project,
Best

2017-09-02 15:43 UTC, sorodrigo requested changes
I also thought of contributing with the Spanish translations. Great job!! I left some edits to stick closer to the original tone of the post. There's also times when another word suits better as a translation. Finally, I marked the translations that are incorrect, and are changing the meaning of the sentence. Take what you like, leave the rest. ✌️

2017-09-02 15:43 UTC, sorodrigo commented on src/texts.js
> +				Desconectándote de Internet cortocircuiteas estos caprichos, lo que te permite avanzar sin obstáculos.
Desconectarse de internet cortocircuita estos caprichos, permitiéndote avanzar sin obstáculos.

> Tone edit, more appropriate translations, cortocircuiteas is incorrect.

2017-09-02 15:43 UTC, sorodrigo commented on src/texts.js
> +				Esta página es un experimento en esa línea: ¿Qué pasaría si para acceder a algunos contenidos fuese obligatorio desconectarse	?
[..] ¿Qué pasaría si para acceder a cierto contenido fuese obligatorio desconectarse?

> Tone edit

2017-09-02 15:43 UTC, sorodrigo commented on src/texts.js
> +				¿Qué pasaría si los lectores tuvieran acceso a esa gloriosa capacidad de atención que te permite devorar una novela durante horas y lo hace tan placentero?
[..] capacidad de atención que hace devorarse una novela durante horas tan placentero?

> More appropriate translations.

2017-09-02 15:43 UTC, sorodrigo commented on src/texts.js
> +				¿O si pudiéramos juntar a los creadores con el poder de los dispositivos modernos?
¿Qué pasaría si los creadores pudieran juntar eso con el poder de los dispositivos modernos?

> Incorrect translation

2017-09-02 15:43 UTC, sorodrigo commented on src/texts.js
> +				Nuestros teléfonos y ordenadores portátiles son plataformas increíbles para crear contenidos siempre y cuando seamos capaces de concentrarnos.
Nuestros teléfonos y ordenadores portátiles son plataformas increíbles para crear contenido creativo—si tan solo pudiéramos explotar nuestra capacidad de atención.

> Incorrect translation

2017-09-02 15:43 UTC, sorodrigo commented on src/texts.js
> +				El contenido disponible sólo en modo sin conexión también puede llevar a los creadores a pensar de manera diferente.
El contenido offline también obliga a los creadores a pensar de manera diferente.

> Incorrect translation

2017-09-02 15:43 UTC, sorodrigo commented on src/texts.js
> +				Cuando estás sin conexión, el único sitio donde puedes estar es aquí.
[..] donde puedes estar es aquí mismo.

> Tone edit (however both versions are good to me)

2017-09-02 15:43 UTC, sorodrigo commented on src/texts.js
> +				Ya oigo las quejas: "Pero tengo que estar conectado para trabajar." Me da igual. Encuentra tiempo.
Ya puedo oír las quejas: "Pero tengo que estar conectado para trabajar." Me da igual. Haz tiempo.

> Incorrect translation.

2017-09-02 15:43 UTC, sorodrigo commented on src/texts.js
> +				Traducido por Javier Blanco García-Lomas.
Traducido por Javier Blanco García-Lomas y Rodrigo Solís.

> 😄  ✌️

2017-09-04 08:33 UTC, jblancogl commented
Hi @sorodrigo! I write you a short message just to thank you for the help. Today I’ll check what you've sent me and I'll merge it

Mil gracias!

2017-09-04 15:51 UTC, chrisbolin commented
@jblancogl and @sorodrigo thank you so much!!! I'm sorry I didn't see this until now

2017-09-04 21:52 UTC, chrisbolin commented
oh nice! @jblancogl did you merge in @sorodrigo's suggestions? that makes it so much easier for me. 👏👏 mi español es no bueno

2017-09-04 22:04 UTC, jblancogl commented
@chrisbolin yes, i did it. all the suggestions were correct and improved the translation. thank you both again!

2017-09-05 06:07 UTC, closed without merging

2017-09-05 06:08 UTC, chrisbolin commented
It's live! https://chris.bolin.co/offline/

(make sure you dump your cache)

![image](https://user-images.githubusercontent.com/2822048/30047416-53c85ba8-91ce-11e7-90ad-ad2d178f0560.png)

2017-09-05 06:46 UTC, jblancogl commented
I can see it! great!

2017-09-05 08:38 UTC, sorodrigo commented
Thanks!! aweeesome